DROP TABLE T_USER IF EXISTS;
CREATE TABLE T_USER
(
  ID VARCHAR(255) NOT NULL,
  CREATE_TIME TIMESTAMP,
  CREATE_USER VARCHAR(255),
  CREATE_USERIP VARCHAR(255),
  DELETED VARCHAR(255),
  UPDATE_TIME TIMESTAMP,
  UPDATE_USER VARCHAR(255),
  UPDATE_USERIP VARCHAR(255),
  VERSION INTEGER,
  AGE INTEGER,
  EMAIL VARCHAR(255),
  FIRST_NAME VARCHAR(255),
  LAST_NAME VARCHAR(255),
  LOCATION VARCHAR(255),
  MOBILE_PHONE VARCHAR(255),
  TIME_ZONE VARCHAR(255),
  USER_NAME VARCHAR(255),
  ACTIVE VARCHAR (10),
  PRIMARY KEY (ID)
);
ALTER TABLE T_USER ADD CONSTRAINT T_USER_USER_NAME_UNIQUE UNIQUE (USER_NAME);
ALTER TABLE T_USER ADD CONSTRAINT T_USER_EMAIL_UNIQUE UNIQUE (EMAIL);
ALTER TABLE T_USER ADD CONSTRAINT T_USER_ACTIVE_CHK CHECK (ACTIVE IN ('YES','NO'));
